FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_TURNSTILE_SITE_KEY
ARG VITE_TELEGRAM_BOT_USERNAME
ARG VITE_FRONTEND_URL
ARG VITE_API_URL
ARG ALLOWED_HOSTS

ENV VITE_TURNSTILE_SITE_KEY=${VITE_TURNSTILE_SITE_KEY}
ENV VITE_TELEGRAM_BOT_USERNAME=${VITE_TELEGRAM_BOT_USERNAME}
ENV VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
ENV VITE_API_URL=${VITE_API_URL}
ENV ALLOWED_HOSTS=${ALLOWED_HOSTS}

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4173

CMD ["nginx", "-g", "daemon off;"]
