services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hackathon-backend
    env_file:
      - ".env"
    environment:
      PORT: ${PORT:-3001}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-hackathon_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      CLIENT_URL: ${CLIENT_URL:-https://chermanx.ru}
      NODE_ENV: ${NODE_ENV:-production}
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY:-}
      MAIN_ADMIN_TELEGRAM_ID: ${MAIN_ADMIN_TELEGRAM_ID:-}

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-5000}:3001"
    networks:
      - internal
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-api.rule=Host(`api.chermanx.ru`)"
      - "traefik.http.routers.backend-api.tls=true"
      - "traefik.http.routers.backend-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-api.loadbalancer.server.port=3001"
      - "traefik.http.routers.backend-api.service=backend-api"

      # HTTP to HTTPS redirect for API
      - "traefik.http.routers.backend-api.middlewares=backend-api-redirect-to-https"
      - "traefik.http.middlewares.backend-api-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.backend-api-redirect-to-https.redirectscheme.permanent=true"

      - "traefik.http.routers.backend-api.middlewares=backend-api-ipallowlist"
      - "traefik.http.middlewares.backend-api-ipallowlist.ipallowlist.sourcerange=127.0.0.1/32, 193.23.3.161"
  db:
    image: postgres:16-alpine
    container_name: hackathon-db
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: ${DB_NAME:-hackathon_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - hackathon_db:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  hackathon_db:

networks:
  internal:
    driver: bridge
  dokploy-network:
    external: true