version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_TELEGRAM_BOT_USERNAME: ${VITE_TELEGRAM_BOT_USERNAME}
        VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
        ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-4173}:4173"
    networks:
      - frontend-network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`chermanx.ru`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=4173"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.frontend.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      - "traefik.http.middlewares.frontend-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.frontend-ratelimit.ratelimit.period=1s"
      - "traefik.http.middlewares.frontend-ratelimit.ratelimit.burst=200"
networks:
  frontend-network:
    name: hackathon-frontend
    driver: bridge
  dokploy-network:
    external: true